# Dependencies
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate"]

# Permalinks
permalink           : pretty

# Setup
title               : Bomy's blog
description         : 'web/all-around developer'
baseurl             : /

author              : Ji-Hui liu
name                : 'Ji-Hui liu'
url                 : https://bomy.github.io/

paginate            : 10

# Custom vars
github_username     : bomy
facebook_username   : jihui.liu
mail_username       : toc00337@gmail.com
